package modelos;
// Generated 05/09/2018 14:24:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombre;
     private String apellido;
     private String dni;
     private float saldoActual;
     private Set transferenciasForOrigen = new HashSet(0);
     private Set transferenciasForDestino = new HashSet(0);
     private Set registros = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nombre, String apellido, String dni, float saldoActual) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
        this.saldoActual = saldoActual;
    }
    public Cliente(String nombre, String apellido, String dni, float saldoActual, Set transferenciasForOrigen, Set transferenciasForDestino, Set registros) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.saldoActual = saldoActual;
       this.transferenciasForOrigen = transferenciasForOrigen;
       this.transferenciasForDestino = transferenciasForDestino;
       this.registros = registros;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public float getSaldoActual() {
        return this.saldoActual;
    }
    
    public void setSaldoActual(float saldoActual) {
        this.saldoActual = saldoActual;
    }
    public Set getTransferenciasForOrigen() {
        return this.transferenciasForOrigen;
    }
    
    public void setTransferenciasForOrigen(Set transferenciasForOrigen) {
        this.transferenciasForOrigen = transferenciasForOrigen;
    }
    public Set getTransferenciasForDestino() {
        return this.transferenciasForDestino;
    }
    
    public void setTransferenciasForDestino(Set transferenciasForDestino) {
        this.transferenciasForDestino = transferenciasForDestino;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


