package modelos;
// Generated 05/09/2018 14:24:47 by Hibernate Tools 4.3.1

/**
 * Registro generated by hbm2java
 */
public class Registro implements java.io.Serializable {

    private Integer idRegistro;
    private Cliente cliente;
    private Transferencia transferencia;
    private String tipo;
    private float estadoSaldoInicio;
    private float estadoSaldoFinal;

    public Registro() {
    }

    public Registro(Cliente cliente, Transferencia transferencia, String tipo) {
        this.cliente = cliente;
        this.transferencia = transferencia;
        this.tipo = tipo;
        if (tipo.equals("Envio")) {
            this.estadoSaldoInicio = this.cliente.getSaldoActual() + transferencia.getCantidad();
            this.estadoSaldoFinal = this.cliente.getSaldoActual();
        } else {
            this.estadoSaldoInicio = this.cliente.getSaldoActual() - transferencia.getCantidad();
            this.estadoSaldoFinal = this.cliente.getSaldoActual();
        }
    }

    public Integer getIdRegistro() {
        return this.idRegistro;
    }

    public void setIdRegistro(Integer idRegistro) {
        this.idRegistro = idRegistro;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Transferencia getTransferencia() {
        return this.transferencia;
    }

    public void setTransferencia(Transferencia transferencia) {
        this.transferencia = transferencia;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public float getEstadoSaldoInicio() {
        return this.estadoSaldoInicio;
    }

    public void setEstadoSaldoInicio(float estadoSaldoInicio) {
        this.estadoSaldoInicio = estadoSaldoInicio;
    }

    public float getEstadoSaldoFinal() {
        return this.estadoSaldoFinal;
    }

    public void setEstadoSaldoFinal(float estadoSaldoFinal) {
        this.estadoSaldoFinal = estadoSaldoFinal;
    }

}
